name: Processor for Forms submission events

on:
  repository_dispatch:
    types: [form-data-received]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Form data processor action
        id: data-processor
        uses: hegupta-adbe/form-data-processor@master
        with:
          google-sa-email: ${{ secrets.GOOGLE_SA_EMAIL }}
          google-sa-pk: ${{ secrets.GOOGLE_SA_PK }}
          google-sheet-id: ${{ vars.GOOGLE_SHEET_ID }}
          sf-instance-url: ${{ vars.SF_INSTANCE_URL }}
          sf-client-id: ${{ secrets.SF_CLIENT_ID }}
          sf-client-secret: ${{ secrets.SF_CLIENT_SECRET }}
          sf-version: ${{ vars.SF_VERSION }}
          sf-type: ${{ vars.SF_TYPE }}
          form-to-sf-mapping: ${{ vars.FORM_TO_SF_MAPPING }}
      - name: Get the result
        run: echo "The result of processing was ${{ steps.data-processor.outputs.processing-result }}"
