name: Processor for Forms submission events

on: [repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: 'echo "secret: ${{ secrets.TEST_SECRET }}"'
    - run: 'echo "payload: ${{ toJson(github.event) }}"'
