name: Processor for Forms submission events

on: [repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Form data processor action
        id: data-processor
        uses: adobe/afb/actions/form-data-processor@4b1236d6a15512344f20cc97e9945b688125b134
        with:
          azure-client-id: 'Dummy ID'
      - name: Get the outpus
        run: echo "The result of processing was ${{ steps.hello.data-processor.processing-result }}"
